### ISSUE TITLE
Not recognizing multiple sourcemaps in the same chunk

### ISSUE THREAD

**Issue by frankieyan** [bugsnag/webpack-bugsnag-plugins#13]
Hi, I'm running into an issue similar to #6 . My app has a single chunk: `[ 'main.css', 'main.js', 'main.css.map', 'main.js.map' ]`. For each chunk, `chunkToSourceMapDescriptor` will only find and select the first `.map` pair it finds, causing the css sourcemap to be the only one to be uploaded.

I'm on Webpack 4.8.3 and webpack-bugsnag-plugins 1.2.1. I'm using mini-css-extract-plugin to extract my css - any help would be appreciated, thanks!

**Comment by bengourley** [comment]
Hey @frankieyan thanks for reporting this. Would you be able to provide more info? 

It would be absolutely amazing if you could provide a `webpack.config.js` and some example files that would reliably reproduce this.

Let me know what you can share, or strip out from your project, and I'll be able to help. Cheers!

**Comment by frankieyan** [comment]
Hey @bengourley - you can check out this repo: https://github.com/frankieyan/bugsnag-upload-repro It emits both main.css and main.js in a single chunk. To handle this I believe `chunkToSourceMapDescriptor` will need walk through a chunk and anticipate multiple files.

Let me know if you need more info - I wouldn't mind taking a crack at the fix too if it helps move things forward 👍

**Comment by bengourley** [comment]
Thanks for the repro repo, so helpful 🌟.

I've (hopefully) fixed this in #14 – I've published a prerelease to npm as `v1.2.2-0`. Do you want to install that and let me know that it fixes your problem?

If it works for you I also just need to route it through our qa procedure, then I can get a stable release out. Cheers!

**Comment by frankieyan** [comment]
Just tested and it works great. Thanks for the quick turnaround @bengourley !
