### ISSUE TITLE
Feature request: Allow to ignore uploading errors

### ISSUE THREAD

**Issue by ryo-utsunomiya** [bugsnag/webpack-bugsnag-plugins#31]
Hi there,

When I run BugsnagSourceMapUploaderPlugin on Windows, sometimes I encountered `ENOTEMPTY` error.

```
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "https://www.ikyu.com/common/dist/chunks/31-df37450caf0ee52e3c02.js"
.\build-assets.bat : Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\appveyor\AppData\Local\Temp\1\bugsnag-sourcemapsm9vVAa'
```

This error occurs when removing not empty directories:
https://github.com/bugsnag/bugsnag-sourcemaps/blob/master/index.js#L345

The root cause of this error is Windows file system and there are no easy solutions.
https://github.com/isaacs/rimraf/issues/72

In my opinion, failure of removing tmp directories is a minor issue. So, I want to ignore this error.

If this plugin provides some error handling option, I can ignore errors.

```
new BugsnagSourceMapUploaderPlugin {
  apiKey: '...',
  publicPath: '...',
  onError: (err, callback) => {
    if (err.code === 'ENOTEMPTY') {
      callback(); // ignore error
    } else {
      callback(err);
    }
  }
}
```

Modification may be something like this:

```diff
BugsnagSourceMapUploaderPlugin {
  constructor(options) {
...
+    this.onError = options.onError
  }
...
  apply(compiler) {
...
      parallel(sourceMaps.map(sm => cb => {
        console.log(`${LOG_PREFIX} uploading sourcemap for "${sm.url}"`)
        upload(this.getUploadOpts(sm), cb)
-      }), 10, callback)
+      }), 10, err => {
+        if (err && this.onError) {
+          this.onError(err, callback)
+        } else {
+         callback(err)
+        }
+      })
...
  }
}
```

What do you think?

**Comment by bengourley** [comment]
The feature request sounds reasonable, but the implementation you suggested means that the occurrence of this error would still stop other source maps from being uploaded, it would just mean the plugin doesn't report the error.

I think the better thing to do would be for us to update the [`bugsnag-sourcemaps` library](https://github.com/bugsnag/bugsnag-sourcemaps) (which is what this module delegates the upload task to) and tolerate `ENOTEMPTY` right where we attempt to remove it.

The change to [this logic](https://github.com/bugsnag/bugsnag-sourcemaps/blob/f3693373f0970ed308281144dd39a9db95242915/index.js#L345-L350) would look something like:


```diff
      fs.rmdir(options.tempDir, (err) => {
-       if (err) {
+       if (err && err.code !== 'ENOTEMPTY') {
          reject(err)
        } else {
          resolve()
        }
```

I'll schedule this change.
