### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by isBatak** [bugsnag/webpack-bugsnag-plugins#32]
Sometimes I get `socket hang up` error during the source map upload and the whole build fails.
```
> Build error occurred

       { Error: socket hang up

           at createHangUpError (_http_client.js:322:15)

           at TLSSocket.socketOnEnd (_http_client.js:425:23)

           at TLSSocket.emit (events.js:187:15)

           at endReadableNT (_stream_readable.js:1092:12)

           at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }

       error Command failed with exit code 1.
```
Has anyone else experienced this problem?

**Comment by isBatak** [comment]
Also, that happened two times in a row on Semaphore CI...

**Comment by bengourley** [comment]
Hey @isBatak, thanks for reporting. We have an open ticket internally to retry on timeouts and other socket errors (such as ECONNRESET). I'll update you when we get around to that. Cheers!

**Comment by bengourley** [comment]
The following releases should be picked up next time you bump your dependencies (`webpack-bugsnag-plugins` depends on these)

https://github.com/bugsnag/bugsnag-build-reporter-node/releases/tag/v1.0.2
https://github.com/bugsnag/bugsnag-sourcemaps/releases/tag/v1.2.0
