### ISSUE TITLE
[FR] add codeBundleId support as upload option

### ISSUE THREAD

**Issue by farfromrefug** [bugsnag/webpack-bugsnag-plugins#38]
Would be really useful

**Comment by abigail-bugsnag** [comment]
Hi @farfromrefug thanks for your comment.

Can I ask if you are using react native? or is there some other reason that you would like to be able to use `codeBundleId`?

It is not recommended to use our webpack plugin with bugsnag-react-native and this is not something that we support. We released a separate API for use with React Native source maps which we'd recommend using, full instructions here:
https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-source-maps

**Comment by farfromrefug** [comment]
@abigail-bugsnag i am not using react native. I am using Nativescript. I wrote a plugin for Nativescript https://github.com/Akylas/nativescript-bugsnag#readme

The bugsnag project is set as a React Native project so that sourcemaps are activated.
But Nativescript uses webpack so i use your webpack plugin which works great for that.
The only thing i miss is ```codeBundleId``` that i set from my Nativescript plugin. So i need it in the webpack plugin.
As your ```bugsnag-sourcemaps``` already supports it, it is just a question of passing the option to it, right?

**Comment by abigail-bugsnag** [comment]
@farfromrefug thanks for the clarification! That makes more sense.
I am sure we can look into adding this for you. We will let you know how this progresses.

**Comment by phillipsam** [comment]
@farfromrefug this has now been released in [v1.4.3](https://github.com/bugsnag/webpack-bugsnag-plugins/releases/tag/v1.4.3)

**Comment by farfromrefug** [comment]
awesome thanks!
