### ISSUE TITLE
publicPath field doesn't work for AWS Lambda + webpack + bugsnag

### ISSUE THREAD

**Issue by Jwalin-Thaker** [bugsnag/webpack-bugsnag-plugins#42]
Tried all the combination of wildcards and file entries, the source map does get uploaded, but it is an incorrect one. Cause it does not trace back to the original source code and just shows the minified weback version instead.

My webpack config (in parts) is as follows:

```
new BugsnagSourceMapUploaderPlugin({
            apiKey: bugsnagApiKey,
            overwrite: true,
            publicPath: 'dist/email-notifications/src/'
          }),
```

```
devtool: 'source-map',
    output: {
      path: join(__dirname, '/dist/email-notifications/src/'),
      filename: 'index.js'
    },
```

My folder structure is as follows:
```
- email-notifications
   - src (has the source code on which webpack works)
       - index.js
       - other folders (with functions called from index.js)
   - dist
       - email-notifications
           - index.js
           - index.js.map
```

My lambda bundle consists of just the `dist/email-notifications/index.js` file

**Comment by phillipsam** [comment]
Hi @Jwalin-Thaker 
Can you please write into support@bugsnag.com with a link to an example of an error which is not symbolicating as you expect?

**Comment by phillipsam** [comment]
Closing as we have not heard back. If you have any further questions, please get in touch.
