### ISSUE TITLE
Encoded URI for source URLs (Next.js)

### ISSUE THREAD

**Issue by macdonaldr93** [bugsnag/webpack-bugsnag-plugins#51]
This is a specific problem with Next.js but I'm wondering how many others might be affected by this.

## Problem

When uploading source map URLs to Bugsnag, the URL uses characters that aren't encoded. For example, `*/_next/chunks/pages/posts/[id]/index-7bb752abed79eb3123b5.js`. When this URL gets loaded in the browser, it tries to match against `*/_next/chunks/pages/posts/%5Bid%5D/index-7bb752abed79eb3123b5.js`. The source map misses.

## Fix

https://github.com/bugsnag/webpack-bugsnag-plugins/blob/b6196c5d0a63fefe120b2f3b84a1aadd9fde2056/source-map-uploader-plugin.js#L83-L87

This `url` should use `encodeURI` so properly escape characters like `[` so that URLs match.

**Comment by johnkiely1** [comment]
Hi @macdonaldr93, 

Thanks for raising, we will look into getting this resolved as soon as we can.

**Comment by johnkiely1** [comment]
@macdonaldr93, 

Would you mind explaining a little more around the usage of [id] within your url? Does this get resolved to be an actual value at some point? As you could replace it with a wildcard * if this changes build to build. 

Would you also have an example from your Bugsnag dashboard where this has failed the mapping. You can send us the link via support@bugsnag.com.

Thanks

**Comment by johnkiely1** [comment]
Hey @macdonaldr93,

Just wanted to check with you if the usage of the wildcard option had been successful? I don't believe we've received any correspondence from you via support@bugsnag.com. Thanks

**Comment by macdonaldr93** [comment]
Yes! Thank you for the reminder. I'm going to get you that feedback today. Sorry about that haha you know how these product roadmaps go.

**Comment by macdonaldr93** [comment]
I can't find any issues with this problem anymore but I can do a better job explaining it.

When the source maps get uploaded they follow `*/_next/chunks/pages/posts/[id]/index-7bb752abed79eb3123b5.js` pattern. The important part here is `[id]`... not any other part of the URL.

When the JavaScript bundle gets downloaded in the actual browser, the `[id]` part of the URL gets encoded so that it's safe for the browser to request. That causes the resource url to be `https://myapp.com/_next/chunks/pages/posts/%5Bid%5D/index-7bb752abed79eb3123b5.js`. When errors happen in this bundle, Bugsnag can't resolve the source map because of the difference between `[id]` and `%5Bid%5D`. `%5B` is the square bracket once it's been encoded. And same for %5D.

My proposal is that these URLs when uploaded should be encoded by default. Browsers won't request resources in a non-encoded way anyways.

Does that make sense?

**Comment by mattdyoung** [comment]
Thanks @macdonaldr93 

Yes, that makes sense. We'll look into what improvements we can make to how this is handled. Thanks!

**Comment by franciscocpg** [comment]
I'm facing exactly the issue with `next-js` and a page using `[lawsuitId]`. Any progress on this?

**Comment by franciscocpg** [comment]
My workaround was removing the brackets from the output filename at `next.config.js`.
```js
const origName = config.output.filename;
config.output.filename = (pathData) => {
  const { name } = pathData.chunk;
  return origName.replace('[name]', name.replace(/(\[|])/g, ''));
};
```

**Comment by mattdyoung** [comment]
This is still on our radar to resolve but other items have taken priority. We'll be sure to update this issue once we've released any improvements. Thanks!

**Comment by RaddishIoW** [comment]
I'm having a related issue:
I use [PNPM](https://pnpm.io/) as my package manager, and it uses "@" characters in the `node_modules` layout, which causes this issue, as the "@" gets encoded on the errors being reported, but not on the source map uploads.

**Comment by RaddishIoW** [comment]
@macdonaldr93 @franciscocpg I created a PR to fix this, but the Bugsnag team are (rightly so) not going to merge it (see their comments on my PR).
I'll maintain my fork which patches this for webpack until they can fix the issue properly. Feel free to use my fork - I'll integrate any upstream changes from Bugsnag.

**Comment by luke-belton** [comment]
Hi @macdonaldr93 - we've made some changes in our backend to normalise URL encoding to ensure URLs are matched correctly between source maps and events 🎉 

Because this is a backend change, you won't need to update your use of Bugsnag for it to take effect 👍
