### ISSUE TITLE
TypeError: Cannot read property 'Debug' of undefined

### ISSUE THREAD

**Issue by pedroassis** [bugsnag/webpack-bugsnag-plugins#56]
I am using webpack version 4.43.0
node 14

When I installed this package @1.7.0 I cannot even require it.

It throws right away.

When I downgraded to @1.4.0 the code stopped throwing.

```js
const { BugsnagSourceMapUploaderPlugin } = require('webpack-bugsnag-plugins')
// ^^^ throws TypeError: Cannot read property 'Debug' of undefined
```

**Comment by xander-jones** [comment]
Hey @pedroassis, not seeing the same results this end using Node 14.15.4, Webpack 4.x, and `webpack-bugsnag-plugins` v1.4.0 or v1.7.0.

The main difference between v1.4.0 and 1.7.0 is that it uses `@bugsnag/source-maps`, our new source map upload CLI instead of the older `bugsnag-sourcemaps`. Does this new package exists in your `node_modules`? Should be `@bugsnag/source-maps@2.1.0` for `webpack-bugsnag-plugins@1.7.0`

Can you share with us a reproduction case of this issue? Is there any more verbose logging that you can share?

**Comment by pedroassis** [comment]
@xander-jones I've found out the require in @bugsnag/source-maps/dist/Logger.js for consola is returning a version from outside of @bugsnag/source-maps

The version from /source-maps is 2.15.0
The version from outside is 2.11.3 (idk how this got there)

consola@2.11.3 does not have a LogLevel prop.

**Comment by johnkiely1** [comment]
Hi @pedroassis,

Yes this dependency resolution conflict issue does look like it's likely to be the problem. 
My understanding is that the dependencies should be automatically resolved pulling in the highest version. Perhaps something is forcing the dependency to be 2.11.3.
 
Could you try run `npm list` to get a dependency tree to understand where the 2.11.3 version is coming from?

**Comment by pedroassis** [comment]
@johnkiely1 

Yes, I haven't dig too much into it, but I also don't understand why it would resolve to a diff version, given the correct one is installed right there.

I could finally reproduce it after looking into my `npm list` as requested

It its webpackbar@3.2.0

If I require `webpackbar` after requiring `webpack-bugsnag-plugins` the error does not happen.

Trimmed tree:
```bash
├─┬ webpack-bugsnag-plugins@1.7.0
│ ├─┬ @bugsnag/source-maps@2.1.0
│ │ ├─┬ command-line-args@5.1.1
│ │ │ ├── array-back@3.1.0
│ │ │ ├─┬ find-replace@3.0.0
│ │ │ │ └── array-back@3.1.0 deduped
│ │ │ ├── lodash.camelcase@4.3.0 deduped
│ │ │ └── typical@4.0.0
│ │ ├─┬ command-line-usage@6.1.1
│ │ │ ├── array-back@4.0.2
│ │ │ ├── chalk@2.4.2 deduped
│ │ │ ├─┬ table-layout@1.0.2
│ │ │ │ ├── array-back@4.0.2
│ │ │ │ ├── deep-extend@0.6.0 deduped
│ │ │ │ ├── typical@5.2.0
│ │ │ │ └─┬ wordwrapjs@4.0.1
│ │ │ │   ├── reduce-flatten@2.0.0
│ │ │ │   └── typical@5.2.0
│ │ │ └── typical@5.2.0
│ │ ├── concat-stream@2.0.0 deduped
│ │ ├── consola@2.15.3
│ │ ├─┬ form-data@3.0.1
│ │ │ ├── asynckit@0.4.0 deduped
│ │ │ ├── combined-stream@1.0.8 deduped
│ │ │ └── mime-types@2.1.26 deduped
│ │ ├── glob@7.1.6 deduped
│ │ └─┬ read-pkg-up@7.0.1
│ │   ├─┬ find-up@4.1.0
│ │   │ ├─┬ locate-path@5.0.0
│ │   │ │ └─┬ p-locate@4.1.0
│ │   │ │   └── p-limit@2.3.0 deduped
│ │   │ └── path-exists@4.0.0
│ │   ├─┬ read-pkg@5.2.0
│ │   │ ├── @types/normalize-package-data@2.4.0
│ │   │ ├── normalize-package-data@2.5.0 deduped
│ │   │ ├─┬ parse-json@5.2.0
│ │   │ │ ├── @babel/code-frame@7.8.3 deduped
│ │   │ │ ├── error-ex@1.3.2 deduped
│ │   │ │ ├── json-parse-even-better-errors@2.3.1 deduped
│ │   │ │ └── lines-and-columns@1.1.6 deduped
│ │   │ └── type-fest@0.6.0
│ │   └── type-fest@0.8.1
│ ├─┬ bugsnag-build-reporter@1.0.3
│ │ ├── chalk@2.4.2 deduped
│ │ ├─┬ concat-stream@1.6.2
│ │ │ ├── buffer-from@1.1.1 deduped
│ │ │ ├── inherits@2.0.4 deduped
│ │ │ ├── readable-stream@2.3.7 deduped
│ │ │ └── typedarray@0.0.6 deduped
│ │ ├── find-nearest-file@1.1.0
│ │ ├─┬ meow@4.0.1
│ │ │ ├─┬ camelcase-keys@4.2.0
│ │ │ │ ├── camelcase@4.1.0
│ │ │ │ ├── map-obj@2.0.0
│ │ │ │ └── quick-lru@1.1.0 deduped
│ │ │ ├── decamelize-keys@1.1.0 deduped
│ │ │ ├── loud-rejection@1.6.0 deduped
│ │ │ ├── minimist@1.2.5 deduped
│ │ │ ├── minimist-options@3.0.2 deduped
│ │ │ ├── normalize-package-data@2.5.0 deduped
│ │ │ ├─┬ read-pkg-up@3.0.0
│ │ │ │ ├── find-up@2.1.0 deduped
│ │ │ │ └─┬ read-pkg@3.0.0
│ │ │ │   ├─┬ load-json-file@4.0.0
│ │ │ │   │ ├── graceful-fs@4.2.3 deduped
│ │ │ │   │ ├─┬ parse-json@4.0.0
│ │ │ │   │ │ ├── error-ex@1.3.2 deduped
│ │ │ │   │ │ └── json-parse-better-errors@1.0.2 deduped
│ │ │ │   │ ├── pify@3.0.0
│ │ │ │   │ └── strip-bom@3.0.0
│ │ │ │   ├── normalize-package-data@2.5.0 deduped
│ │ │ │   └─┬ path-type@3.0.0
│ │ │ │     └── pify@3.0.0 deduped
│ │ │ ├─┬ redent@2.0.0
│ │ │ │ ├── indent-string@3.2.0
│ │ │ │ └── strip-indent@2.0.0
│ │ │ └── trim-newlines@2.0.0
│ │ ├── minimist@1.2.5 deduped
│ │ ├── once@1.4.0 deduped
│ │ ├─┬ pino@4.17.6
│ │ │ ├── chalk@2.4.2 deduped
│ │ │ ├── fast-json-parse@1.0.3
│ │ │ ├── fast-safe-stringify@1.2.3
│ │ │ ├── flatstr@1.0.12
│ │ │ ├── pino-std-serializers@2.5.0
│ │ │ ├─┬ pump@3.0.0
│ │ │ │ ├── end-of-stream@1.4.4 deduped
│ │ │ │ └── once@1.4.0 deduped
│ │ │ ├─┬ quick-format-unescaped@1.1.2
│ │ │ │ └── fast-safe-stringify@1.2.3
│ │ │ └─┬ split2@2.2.0
│ │ │   └─┬ through2@2.0.5
│ │ │     ├── readable-stream@2.3.7 deduped
│ │ │     └── xtend@4.0.2 deduped
│ │ └── run-parallel@1.1.9
│ └─┬ run-parallel-limit@1.1.0
│   └── queue-microtask@1.2.3
├─┬ webpackbar@3.2.0
│ ├─┬ ansi-escapes@4.3.1
│ │ └── type-fest@0.11.0
│ ├── chalk@2.4.2 deduped
│ ├── consola@2.11.3
│ ├─┬ figures@3.2.0
│ │ └── escape-string-regexp@1.0.5 deduped
│ ├── pretty-time@1.1.0
│ ├─┬ std-env@2.2.1
│ │ └── ci-info@1.6.0
│ ├── text-table@0.2.0 deduped
│ └─┬ wrap-ansi@5.1.0
│   ├── ansi-styles@3.2.1 deduped
│   ├─┬ string-width@3.1.0
│   │ ├── emoji-regex@7.0.3 deduped
│   │ ├── is-fullwidth-code-point@2.0.0
│   │ └── strip-ansi@5.2.0 deduped
│   └─┬ strip-ansi@5.2.0
│     └── ansi-regex@4.1.0
```

**Comment by johnkiely1** [comment]
Hi @pedroassis. 

I've tried reproducing the scenario you are describing, but for me it will always import v2.15.3 of consola, even without using the Bugsnag webpack plugin. 

If you are happy it is now working by adjusting the dependency ordering, that I would suggest sticking with that, otherwise you could try deleting your entire `node_modules` folder and rerunning `npm i` to re import everything. Perhaps it has just cached some of the dependencies strangely.

**Comment by pedroassis** [comment]
I tried deleting my entire `node_modules` too, it reinstalled the same way.

It looks like a bug somewhere else, I'll close the issue, thanks everyone.
