### ISSUE TITLE
Not working with webpack 4

### ISSUE THREAD

**Issue by razagill** [bugsnag/webpack-bugsnag-plugins#6]
Hi it looks like the plugin isn't working with webpack 4.
There is a small warning about using `.hooks`, which can easily be correct by using `compiler.hooks.afterEmit.tapAsync(...`

However, the main issue I'm having is that I'm getting my chunks something like this: (so `stats.chunks.length` is `2`)
```
[ 'vendor.css',
  'vendor.fc6c3b79.js',
  'vendor.css.map',
  'vendor.fc6c3b79.js.map' ],
[ 'main.css',
  'main.da7c09d0.js',
  'main.css.map',
  'main.da7c09d0.js.map' ]
```
And so in the `chunkToSourceMapDescriptor` it's only picking up the first `*.css.map` files and uploads them. I'm not sure if I need to change my webpack config or do we need to adapt the plugin. Any help is appreciated.

**Comment by bengourley** [comment]
Hi @razagill thanks for the issue. We're planning to release an update for Webpack 4 soon!

**Comment by ryo-utsunomiya** [comment]
Hi, @bengourley. Are there any updates on Webpack 4 support?
Maybe we can use `compiler.hooks.afterEmit.tap()` instead of `compiler.plugin('after-emit')`.

**Comment by razagill** [comment]
@ryo-utsunomiya That won't solve the actual issue. I tried it and still got another problem (read the first comment for more detail).
But yes, @bengourley are there any updates?

**Comment by bengourley** [comment]
Hi. Sorry for the delay, we've had a lot of product work going on which meant that this has not reached the top of my todo list yet. I'm going to attempt to get it to the top of the priority pile in the next week or two, as I'm aware the longer it goes on the more people it's going to affect as they upgrade webpack.

**Comment by bengourley** [comment]
@razagill I've been looking into what's required for this today. I can't see a situation where `stats.chunks` is a nested array rather than a flat array of chunks. 

Are you able to provide a reproducible example or your webpack config at all?
