### ISSUE TITLE
Metadata is not listed as a build opt

### ISSUE THREAD

**Issue by charliegroll** [bugsnag/webpack-bugsnag-plugins#66]
### Describe the bug
The README doesn't mention `metadata` as a `build` argument, although it's [accepted](https://github.com/bugsnag/bugsnag-build-reporter-node/blob/e3f802bc9c0fa965ce706834cbdec9842cab2e09/lib/schema.js#L25-L34) 

Reference from https://bugsnagbuildapi.docs.apiary.io/#introduction/source-control: 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1126370/135507891-01ea89b7-0151-447b-bdc7-a6cab216cf5e.png">

**Comment by charliegroll** [comment]
https://github.com/bugsnag/webpack-bugsnag-plugins/pull/67

**Comment by johnkiely1** [comment]
Hi @charliegroll. 

Thanks for the PR, I'm going to close this any we can continue any necessary discussion on the PR itself.
