### ISSUE TITLE
Source maps is not differentiate by release stages

### ISSUE THREAD

**Issue by qisoft** [bugsnag/webpack-bugsnag-plugins#7]
You can run different sources on different stages, but you only can use one source map per app version. Now the only workaround is to append release stage to the app version. Would be great to have differentiation on release stages for source maps.

**Comment by bengourley** [comment]
Hi @qisoft.

Let me try to understand your setup first: are you saying that for a given version number (say v1.2.3) your application code can be different depending on which release stage it is at?

If this is the case I would suggest that this is not a good idea – having stable and unique version numbers makes things easier to deal with. By appending the release stage to the version number, it makes this unique and the problem goes away (as you discovered!)

However, we do cater for the (definitiely not recommended) use case. You just have to be a bit more specific with the `publicUrl` for your uploaded source maps. e.g.

**Staging**

```diff
+ publicUrl: 'http*://staging.my-cool.app/static/'
- publicUrl: '*/static/'
```

**Production**

```diff
+ publicUrl: 'http*://www.my-cool.app/static/'
- publicUrl: '*/static/'
```

Hope this helps!
Cheers
